name: peak_predictor
description: Forecasts busy days and busy hours on Malaysian rail using open government data.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  http: ^1.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
